### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jhubert** [goldstar/newrelic-elasticsearch#8]
Hi there,

We're considering using this gem but noticed that it doesn't have a license. Are you willing to make it freely available to other people? If so, it would be great if you would consider adding a license.

I'd be happy to submit a PR for an MIT license if it's helpful, but I don't want to be too presumptuous. If you're unfamiliar with the licensing process, GitHub has created [choosealicense.com](https://choosealicense.com/) to help sort it out.

Thanks for sharing your gem!

Warmly,
Jeremy

**Comment by stephenprater** [comment]
Sounds great.  @therubymug MIT work for this?

**Comment by jhubert** [comment]
You didn’t ask me, but I say yes! 🤩

**Comment by therubymug** [comment]
Done. https://github.com/goldstar/newrelic-elasticsearch/commit/8bbc2cc98c52e6b71b1a55e84ed59fb7e922509f
